### ISSUE TITLE
[Feature request] Add export support for text strings

### ISSUE THREAD

**Issue by mk360** [SkyTemple/skytemple#129] opened 2020-12-27 19:50 UTC
It's pretty straight-forward: allow the end-user to export text strings (french, german, etc.). So far we can't manipulate them in any way, shape or form. Being able to export all categories at once (as well as exporting specific categories) would be nice as well.

**Comment by Parakoopa** [comment] 2020-12-27 20:37
Duplicate of #97

**Closed** 2020-12-27 20:37 UTC
